.TH "PBCTL" "1" "" "" "User Commands"
.SH "NAME"
\fBpbctl\fR

.SH "SYNOPSIS"
PulseBlaster control program. Simple perl script to program and stop/start/arm/continue the pulseblaster.

.SH "COMMANDS"
.LP 
\fBpbctl -h\fR
.IP 
Invoke pbctl with -h for further details.

.SH "SEE ALSO"
\fBpulseblaster\fR(1), \fBpb_utils\fR(1)
