.TH "PB_TESTS" "1" "July 2012" "IR Camera System" "User Commands"
.SH "NAME"
\fBpb_test-pbinit-counter\fR, \fBpb_test-vliw-walk4\fR

.SH "SYNOPSIS"
These are tests of pb_utils. 

.SH "COMMANDS"
.LP 
\fBpb_test-pbinit-counter\fR
.IP 
This tests that pb_init works, by emulating a binary counter (the "hard way"). It is a test of pb_utils.
It may be invoked with \fB-h\fR for help.

.LP 
\fBpb_test-vliw-walk4\fR
.IP 
This is a test of vliw programming, also verifying pb_prog. It flashes the LEDs in a 4-step walking pattern.
It may be invoked with \fB-h\fR for help.

.SH "SEE ALSO"
\fBpulseblaster\fR(1), \fBpb_utils\fR(1)

